baseURL = "https://www.michaelkelly.org"
languageCode = "en-us"
title = "michaelkelly.org"
# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds = ["taxonomy", "taxonomyTerm"]
